/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Telecom } from './Telecom';

/**
 * the list of addresses (with address type).
 */
import {decodeBase64} from "./ModelHelper";

export class Address { 
    constructor(json: JSON | any) {
        Object.assign(this as Address, json)
    }

    addressType?: Address.AddressTypeEnum;
    description?: string;
    street?: string;
    houseNumber?: string;
    postboxNumber?: string;
    postalCode?: string;
    city?: string;
    state?: string;
    country?: string;
    note?: string;
    telecoms?: Array<Telecom>;
}
export namespace Address {
    export type AddressTypeEnum = 'home' | 'work' | 'vacation' | 'hospital' | 'clinic' | 'hq' | 'other' | 'temporary' | 'postal' | 'diplomatic' | 'reference';
    export const AddressTypeEnum = {
        Home: 'home' as AddressTypeEnum,
        Work: 'work' as AddressTypeEnum,
        Vacation: 'vacation' as AddressTypeEnum,
        Hospital: 'hospital' as AddressTypeEnum,
        Clinic: 'clinic' as AddressTypeEnum,
        Hq: 'hq' as AddressTypeEnum,
        Other: 'other' as AddressTypeEnum,
        Temporary: 'temporary' as AddressTypeEnum,
        Postal: 'postal' as AddressTypeEnum,
        Diplomatic: 'diplomatic' as AddressTypeEnum,
        Reference: 'reference' as AddressTypeEnum
    };
}

