/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Encrypted and time-limited Authentication tokens used for inter-applications authentication
 */
import {decodeBase64} from "./ModelHelper";

export class AuthenticationToken { 
    constructor(json: JSON | any) {
        Object.assign(this as AuthenticationToken, json)
    }

    /**
     * Encrypted token
     */
    token?: string;
    /**
     * Validity starting time of the token
     */
    creationTime?: number;
    /**
     * Token validity in seconds
     */
    validity?: number;
}

