/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Codified list of professions exercised by this patient.
 */
import {decodeBase64} from "./ModelHelper";

export class CodingReference { 
    constructor(json: JSON | any) {
        Object.assign(this as CodingReference, json)
    }

    id?: string;
    type?: string;
    code?: string;
    version?: string;
}

