/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataSample } from './DataSample';
import { Measure } from './Measure';
import { TimeSeries } from './TimeSeries';

/**
 * Information contained in the data sample. Content is localized, using ISO language code as key
 */
import {decodeBase64} from "./ModelHelper";

export class Content { 
    constructor(json: JSON | any) {
        Object.assign(this as Content, json)
    }

    stringValue?: string;
    numberValue?: number;
    booleanValue?: boolean;
    instantValue?: Date;
    /**
     * Value as date. The format could have a all three (day, month and year) or values on any of these three, whatever is known.
     */
    fuzzyDateValue?: number;
    binaryValue?: string;
    /**
     * Linked document.
     */
    documentId?: string;
    measureValue?: Measure;
    timeSeries?: TimeSeries;
    compoundValue?: Array<DataSample>;
    ratio?: Array<Measure>;
    range?: Array<Measure>;
}

