/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodingReference } from './CodingReference';
import { Content } from './Content';
import { Identifier } from './Identifier';

import {decodeBase64} from "./ModelHelper";

export class DataSample { 
    constructor(json: JSON | any) {
        Object.assign(this as DataSample, json)
    }

    /**
     * The Id of the Data sample. We encourage using either a v4 UUID or a HL7 Id.
     */
    id?: string;
    /**
     * The transactionId is used when a single data sample had to be split into parts for technical reasons. Several data samples with the same non null transaction id form one single data sample
     */
    transactionId?: string;
    identifier?: Array<Identifier>;
    /**
     * Id of the batch that embeds this data sample
     */
    batchId?: string;
    /**
     * List of IDs of all healthcare elements for which the data sample is provided. Only used when the Data sample is emitted outside of its contact
     */
    healthElementsIds?: Array<string>;
    /**
     * List of Ids of all canvases linked to the Data sample. Only used when the Data sample is emitted outside of its contact.
     */
    canvasesIds?: Array<string>;
    /**
     * Used for sorting data samples inside an upper object (A contact, a transaction, a FHIR bundle, ...)
     */
    index?: number;
    /**
     * Information contained in the data sample. Content is localized, using ISO language code as key
     */
    content?: { [key: string]: Content; };
    /**
     * The date (YYYYMMDDhhmmss) when the Data sample is noted to have started and also closes on the same date
     */
    valueDate?: number;
    /**
     * The date (YYYYMMDDhhmmss) of the start of the Data sample
     */
    openingDate?: number;
    /**
     * The date (YYYYMMDDhhmmss) marking the end of the Data sample
     */
    closingDate?: number;
    created?: number;
    modified?: number;
    endOfLife?: number;
    author?: string;
    responsible?: string;
    /**
     * Text, comments on the Data sample provided
     */
    comment?: string;
    /**
     * Links towards related data samples (possibly in other contacts)
     */
    qualifiedLinks?: { [key: string]: { [key: string]: string; }; };
    codes?: Array<CodingReference>;
    labels?: Array<CodingReference>;
}

