/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodingReference } from './CodingReference';

import {decodeBase64} from "./ModelHelper";

export class Identifier { 
    constructor(json: JSON | any) {
        Object.assign(this as Identifier, json)
    }

    id?: string;
    assigner?: string;
    start?: string;
    end?: string;
    system?: string;
    type?: CodingReference;
    use?: string;
    value?: string;
}

