/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodingReference } from './CodingReference';

import {decodeBase64} from "./ModelHelper";

export class Measure { 
    constructor(json: JSON | any) {
        Object.assign(this as Measure, json)
    }

    value?: number;
    min?: number;
    max?: number;
    ref?: number;
    severity?: number;
    severityCode?: string;
    evolution?: number;
    unit?: string;
    unitCodes?: Array<CodingReference>;
    comment?: string;
    comparator?: string;
}

