/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodingReference } from './CodingReference';
import { Identifier } from './Identifier';
import { Property } from './Property';

import {decodeBase64} from "./ModelHelper";

export class MedicalDevice { 
    constructor(json: JSON | any) {
        Object.assign(this as MedicalDevice, json, json.picture ? { picture: decodeBase64(json.picture) } : {})
    }

    id?: string;
    rev?: string;
    deletionDate?: number;
    identifiers?: Array<Identifier>;
    created?: number;
    modified?: number;
    author?: string;
    responsible?: string;
    labels?: Array<CodingReference>;
    codes?: Array<CodingReference>;
    endOfLife?: number;
    externalId?: string;
    name?: string;
    type?: string;
    brand?: string;
    model?: string;
    serialNumber?: string;
    parentId?: string;
    picture?: ArrayBuffer;
    properties?: Array<Property>;
}

