/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HealthcareProfessional } from './HealthcareProfessional';
import { PaginatedDocumentKeyAndIdPairObject } from './PaginatedDocumentKeyAndIdPairObject';

import {decodeBase64} from "./ModelHelper";

export class PaginatedListHealthcareProfessional { 
    constructor(json: JSON | any) {
        Object.assign(this as PaginatedListHealthcareProfessional, json)
    }

    pageSize?: number;
    totalSize?: number;
    rows?: Array<HealthcareProfessional>;
    nextKeyPair?: PaginatedDocumentKeyAndIdPairObject;
}

