/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Links (usually for therapeutic reasons) between this patient and healthcare parties (of class PatientHealthcareParty).
 */
import {decodeBase64} from "./ModelHelper";

export class PatientHealthCareParty { 
    constructor(json: JSON | any) {
        Object.assign(this as PatientHealthCareParty, json)
    }

    type?: PatientHealthCareParty.TypeEnum;
    healthcarePartyId?: string;
}
export namespace PatientHealthCareParty {
    export type TypeEnum = 'doctor' | 'referral' | 'medicalhouse' | 'retirementhome' | 'hospital' | 'other' | 'referringphysician' | 'managingorganization';
    export const TypeEnum = {
        Doctor: 'doctor' as TypeEnum,
        Referral: 'referral' as TypeEnum,
        Medicalhouse: 'medicalhouse' as TypeEnum,
        Retirementhome: 'retirementhome' as TypeEnum,
        Hospital: 'hospital' as TypeEnum,
        Other: 'other' as TypeEnum,
        Referringphysician: 'referringphysician' as TypeEnum,
        Managingorganization: 'managingorganization' as TypeEnum
    };
}

