/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './Address';
import { CodingReference } from './CodingReference';
import { Identifier } from './Identifier';
import { Partnership } from './Partnership';
import { PatientHealthCareParty } from './PatientHealthCareParty';
import { PersonName } from './PersonName';
import { Property } from './Property';

import {decodeBase64} from "./ModelHelper";

export class Patient { 
    constructor(json: JSON | any) {
        Object.assign(this as Patient, json)
    }

    /**
     * the Id of the patient. We encourage using either a v4 UUID or a HL7 Id.
     */
    id?: string;
    /**
     * the revision of the patient in the database, used for conflict management / optimistic locking.
     */
    rev?: string;
    identifier?: Array<Identifier>;
    created?: number;
    modified?: number;
    author?: string;
    responsible?: string;
    labels?: Array<CodingReference>;
    codes?: Array<CodingReference>;
    endOfLife?: number;
    deletionDate?: number;
    /**
     * the firstname (name) of the patient.
     */
    firstName?: string;
    /**
     * the lastname (surname) of the patient. This is the official lastname that should be used for official administrative purposes.
     */
    lastName?: string;
    /**
     * the list of all names of the patient, also containing the official full name information. Ordered by preference of use. First element is therefore the official name used for the patient in the application
     */
    names?: Array<PersonName>;
    /**
     * the name of the company this patient is member of.
     */
    companyName?: string;
    /**
     * the list of languages spoken by the patient ordered by fluency (alpha-2 code http://www.loc.gov/standards/iso639-2/ascii_8bits.html).
     */
    languages?: Array<string>;
    /**
     * the list of addresses (with address type).
     */
    addresses?: Array<Address>;
    /**
     * Mr., Ms., Pr., Dr. ...
     */
    civility?: string;
    /**
     * the gender of the patient: male, female, indeterminate, changed, changedToMale, changedToFemale, unknown
     */
    gender?: Patient.GenderEnum;
    /**
     * the birth sex of the patient: male, female, indeterminate, unknown
     */
    birthSex?: Patient.BirthSexEnum;
    /**
     * The id of the patient this patient has been merged with.
     */
    mergeToPatientId?: string;
    /**
     * The ids of the patients that have been merged inside this patient.
     */
    mergedIds?: Array<string>;
    /**
     * An alias of the person, nickname, ...
     */
    alias?: string;
    /**
     * Is the patient active (boolean).
     */
    active?: boolean;
    /**
     * When not active, the reason for deactivation.
     */
    deactivationReason?: Patient.DeactivationReasonEnum;
    /**
     * Social security inscription number.
     */
    ssin?: string;
    /**
     * Lastname at birth (can be different of the current name), depending on the country, must be used to design the patient .
     */
    maidenName?: string;
    /**
     * Lastname of the spouse for a married woman, depending on the country, can be used to design the patient.
     */
    spouseName?: string;
    /**
     * Lastname of the partner, should not be used to design the patient.
     */
    partnerName?: string;
    /**
     * any of `single`, `in_couple`, `married`, `separated`, `divorced`, `divorcing`, `widowed`, `widower`, `complicated`, `unknown`, `contract`, `other`.
     */
    personalStatus?: Patient.PersonalStatusEnum;
    /**
     * The birthdate encoded as a fuzzy date on 8 positions (YYYYMMDD) MM and/or DD can be set to 00 if unknown (19740000 is a valid date).
     */
    dateOfBirth?: number;
    /**
     * The date of death encoded as a fuzzy date on 8 positions (YYYYMMDD) MM and/or DD can be set to 00 if unknown (19740000 is a valid date).
     */
    dateOfDeath?: number;
    /**
     * The place of birth.
     */
    placeOfBirth?: string;
    /**
     * The place of death.
     */
    placeOfDeath?: string;
    /**
     * Is the patient deceased.
     */
    deceased?: boolean;
    /**
     * The level of education (college degree, undergraduate, phd).
     */
    education?: string;
    /**
     * The current professional activity.
     */
    profession?: string;
    /**
     * A text note (can be confidential, encrypted by default).
     */
    note?: string;
    /**
     * An administrative note, not confidential.
     */
    administrativeNote?: string;
    /**
     * The nationality of the patient.
     */
    nationality?: string;
    /**
     * The race of the patient.
     */
    race?: string;
    /**
     * The ethnicity of the patient.
     */
    ethnicity?: string;
    /**
     * A picture usually saved in JPEG format.
     */
    picture?: string;
    /**
     * An external (from another source) id with no guarantee or requirement for unicity .
     */
    externalId?: string;
    /**
     * List of partners, or persons of contact (of class Partnership, see below).
     */
    partnerships?: Array<Partnership>;
    /**
     * Links (usually for therapeutic reasons) between this patient and healthcare parties (of class PatientHealthcareParty).
     */
    patientHealthCareParties?: Array<PatientHealthCareParty>;
    /**
     * Codified list of professions exercised by this patient.
     */
    patientProfessions?: Array<CodingReference>;
    /**
     * Extra parameters
     */
    parameters?: { [key: string]: Array<string>; };
    /**
     * Extra properties
     */
    properties?: Array<Property>;
}
export namespace Patient {
    export type GenderEnum = 'M' | 'F' | 'I' | 'C' | 'Y' | 'X' | 'U';
    export const GenderEnum = {
        M: 'M' as GenderEnum,
        F: 'F' as GenderEnum,
        I: 'I' as GenderEnum,
        C: 'C' as GenderEnum,
        Y: 'Y' as GenderEnum,
        X: 'X' as GenderEnum,
        U: 'U' as GenderEnum
    };
    export type BirthSexEnum = 'M' | 'F' | 'I' | 'C' | 'Y' | 'X' | 'U';
    export const BirthSexEnum = {
        M: 'M' as BirthSexEnum,
        F: 'F' as BirthSexEnum,
        I: 'I' as BirthSexEnum,
        C: 'C' as BirthSexEnum,
        Y: 'Y' as BirthSexEnum,
        X: 'X' as BirthSexEnum,
        U: 'U' as BirthSexEnum
    };
    export type DeactivationReasonEnum = 'deceased' | 'moved' | 'other_doctor' | 'retired' | 'no_contact' | 'unknown' | 'none';
    export const DeactivationReasonEnum = {
        Deceased: 'deceased' as DeactivationReasonEnum,
        Moved: 'moved' as DeactivationReasonEnum,
        OtherDoctor: 'other_doctor' as DeactivationReasonEnum,
        Retired: 'retired' as DeactivationReasonEnum,
        NoContact: 'no_contact' as DeactivationReasonEnum,
        Unknown: 'unknown' as DeactivationReasonEnum,
        None: 'none' as DeactivationReasonEnum
    };
    export type PersonalStatusEnum = 'single' | 'in_couple' | 'married' | 'separated' | 'divorced' | 'divorcing' | 'widowed' | 'widower' | 'complicated' | 'unknown' | 'contract' | 'other' | 'annulled' | 'polygamous';
    export const PersonalStatusEnum = {
        Single: 'single' as PersonalStatusEnum,
        InCouple: 'in_couple' as PersonalStatusEnum,
        Married: 'married' as PersonalStatusEnum,
        Separated: 'separated' as PersonalStatusEnum,
        Divorced: 'divorced' as PersonalStatusEnum,
        Divorcing: 'divorcing' as PersonalStatusEnum,
        Widowed: 'widowed' as PersonalStatusEnum,
        Widower: 'widower' as PersonalStatusEnum,
        Complicated: 'complicated' as PersonalStatusEnum,
        Unknown: 'unknown' as PersonalStatusEnum,
        Contract: 'contract' as PersonalStatusEnum,
        Other: 'other' as PersonalStatusEnum,
        Annulled: 'annulled' as PersonalStatusEnum,
        Polygamous: 'polygamous' as PersonalStatusEnum
    };
}

