/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * the list of all names of the patient, also containing the official full name information. Ordered by preference of use. First element is therefore the official name used for the patient in the application
 */
import {decodeBase64} from "./ModelHelper";

export class PersonName { 
    constructor(json: JSON | any) {
        Object.assign(this as PersonName, json)
    }

    lastName?: string;
    firstNames?: Array<string>;
    start?: number;
    end?: number;
    prefix?: Array<string>;
    suffix?: Array<string>;
    text?: string;
    use?: PersonName.UseEnum;
}
export namespace PersonName {
    export type UseEnum = 'usual' | 'official' | 'temp' | 'nickname' | 'anonymous' | 'maiden' | 'old' | 'other';
    export const UseEnum = {
        Usual: 'usual' as UseEnum,
        Official: 'official' as UseEnum,
        Temp: 'temp' as UseEnum,
        Nickname: 'nickname' as UseEnum,
        Anonymous: 'anonymous' as UseEnum,
        Maiden: 'maiden' as UseEnum,
        Old: 'old' as UseEnum,
        Other: 'other' as UseEnum
    };
}

