/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {decodeBase64} from "./ModelHelper";

export class Telecom { 
    constructor(json: JSON | any) {
        Object.assign(this as Telecom, json)
    }

    telecomType?: Telecom.TelecomTypeEnum;
    telecomNumber?: string;
    telecomDescription?: string;
}
export namespace Telecom {
    export type TelecomTypeEnum = 'mobile' | 'phone' | 'email' | 'fax' | 'skype' | 'im' | 'medibridge' | 'ehealthbox' | 'apicrypt' | 'web' | 'print' | 'disk' | 'other' | 'pager';
    export const TelecomTypeEnum = {
        Mobile: 'mobile' as TelecomTypeEnum,
        Phone: 'phone' as TelecomTypeEnum,
        Email: 'email' as TelecomTypeEnum,
        Fax: 'fax' as TelecomTypeEnum,
        Skype: 'skype' as TelecomTypeEnum,
        Im: 'im' as TelecomTypeEnum,
        Medibridge: 'medibridge' as TelecomTypeEnum,
        Ehealthbox: 'ehealthbox' as TelecomTypeEnum,
        Apicrypt: 'apicrypt' as TelecomTypeEnum,
        Web: 'web' as TelecomTypeEnum,
        Print: 'print' as TelecomTypeEnum,
        Disk: 'disk' as TelecomTypeEnum,
        Other: 'other' as TelecomTypeEnum,
        Pager: 'pager' as TelecomTypeEnum
    };
}

