/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A high frequency time-series containing the ts in ms from the start (double) and the values
 */
import {decodeBase64} from "./ModelHelper";

export class TimeSeries { 
    constructor(json: JSON | any) {
        Object.assign(this as TimeSeries, json)
    }

    fields?: Array<string>;
    samples?: Array<Array<number>>;
    min?: Array<number>;
    max?: Array<number>;
    mean?: Array<number>;
    median?: Array<number>;
    variance?: Array<number>;
}

