repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
        additional_dependencies:
          - pyahocorasick==1.4.4
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.1' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.6.2
