/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {Telecom} from './Telecom';

/**
* the list of addresses (with address type).
*/
export class Address {
constructor(json: IAddress) {
  const { addressType, telecoms, ...simpleProperties } = json

  Object.assign(this as Address, simpleProperties)

  this.addressType = addressType as AddressAddressTypeEnum
  this.telecoms = telecoms?.map(t => new Telecom(t)) ?? []
}

    'addressType'?: AddressAddressTypeEnum;
    'description'?: string;
    'street'?: string;
    'houseNumber'?: string;
    'postboxNumber'?: string;
    'postalCode'?: string;
    'city'?: string;
    'state'?: string;
    'country'?: string;
    'note'?: string;
    'telecoms': Array<Telecom>;

    marshal(): IAddress {
      return {
        ...this,
        telecoms: this.telecoms.map(t => t.marshal()),
      }
    }
}

interface IAddress {
  'addressType'?: AddressAddressTypeEnum;
  'description'?: string;
  'street'?: string;
  'houseNumber'?: string;
  'postboxNumber'?: string;
  'postalCode'?: string;
  'city'?: string;
  'state'?: string;
  'country'?: string;
  'note'?: string;
  'telecoms'?: Array<Telecom>;
}


export type AddressAddressTypeEnum = "home" | "work" | "vacation" | "hospital" | "clinic" | "hq" | "other" | "temporary" | "postal" | "diplomatic" | "reference" ;
