/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Document {
constructor(json: IDocument) {
  Object.assign(this as Document, json)
}

    /**
    * The Id of the document. We encourage using either a v4 UUID or a HL7 Id.
    */
    'id'?: string;
    /**
    * The revision of the document in the database, used for conflict management / optimistic locking.
    */
    'rev'?: string;
    'created'?: number;
    'modified'?: number;
    'author'?: string;
    'responsible'?: string;
    'medicalLocationId'?: string;
    'deletionDate'?: number;
    /**
    * Reference in object store
    */
    'objectStoreReference'?: string;
    /**
    * The main Uniform Type Identifier of the document (https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE)
    */
    'mainUti'?: string;
    /**
    * Name of the document
    */
    'name'?: string;
    /**
    * The document version
    */
    'version'?: string;
    /**
    * Extra Uniform Type Identifiers
    */
    'otherUtis': Set<string>;
    /**
    * A unique external id (from another external source).
    */
    'externalUuid'?: string;
    /**
    * Size of the document file
    */
    'size'?: number;
    /**
    * Hashed version of the document
    */
    'hash'?: string;
    /**
    * Id of attachment to this document
    */
    'attachmentId'?: string;

}

interface IDocument {
  'id'?: string;
  'rev'?: string;
  'created'?: number;
  'modified'?: number;
  'author'?: string;
  'responsible'?: string;
  'medicalLocationId'?: string;
  'deletionDate'?: number;
  'objectStoreReference'?: string;
  'mainUti'?: string;
  'name'?: string;
  'version'?: string;
  'otherUtis'?: Set<string>;
  'externalUuid'?: string;
  'size'?: number;
  'hash'?: string;
  'attachmentId'?: string;
}

