/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Filter {
constructor(json: IFilter) {
  Object.assign(this as Filter, json)
}

    'description': string;

    marshal(): IFilter {
      return {
        ...this,
      }
    }
}

interface IFilter {
  'description'?: string;
}
