/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class InlineResponse403 {
constructor(json: IInlineResponse403) {
  Object.assign(this as InlineResponse403, json)
}

    '_short'?: number;
    '_char'?: string;
    '_int'?: number;
    '_long'?: number;
    '_float'?: number;
    '_double'?: number;
    'direct'?: boolean;
    'readOnly'?: boolean;

}

interface IInlineResponse403 {
  '_short'?: number;
  '_char'?: string;
  '_int'?: number;
  '_long'?: number;
  '_float'?: number;
  '_double'?: number;
  'direct'?: boolean;
  'readOnly'?: boolean;
}
