/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {CodingReference} from './CodingReference';

export class Measure {
constructor(json: IMeasure) {
  Object.assign(this as Measure, json)
}

    'value'?: number;
    'min'?: number;
    'max'?: number;
    'ref'?: number;
    'severity'?: number;
    'severityCode'?: string;
    'evolution'?: number;
    'unit'?: string;
    'unitCodes'?: Set<CodingReference>;
    'comment'?: string;
    'comparator'?: string;

}

interface IMeasure {
  'value'?: number;
  'min'?: number;
  'max'?: number;
  'ref'?: number;
  'severity'?: number;
  'severityCode'?: string;
  'evolution'?: number;
  'unit'?: string;
  'unitCodes'?: Set<CodingReference>;
  'comment'?: string;
  'comparator'?: string;
}

