/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PaginatedDocumentKeyAndIdPairObject {
constructor(json: IPaginatedDocumentKeyAndIdPairObject) {
  Object.assign(this as PaginatedDocumentKeyAndIdPairObject, json)
}

    'startKey'?: any;
    'startKeyDocId'?: string;

}

interface IPaginatedDocumentKeyAndIdPairObject {
  'startKey'?: any;
  'startKeyDocId'?: string;
}

