/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {HealthcareElement} from './HealthcareElement';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListHealthcareElement {
constructor(json: IPaginatedListHealthcareElement) {
  Object.assign(this as PaginatedListHealthcareElement, json)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<HealthcareElement>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

}

interface IPaginatedListHealthcareElement {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<HealthcareElement>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
