/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';
import {Patient} from './Patient';

export class PaginatedListPatient {
constructor(json: IPaginatedListPatient) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListPatient, simpleProperties as IPaginatedListPatient)

  this.rows = rows ? [...rows]?.map(p => new Patient(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<Patient>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListPatient {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListPatient {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<Patient>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
