/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {DataSample} from './DataSample';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';
import {Coding} from "./Coding";

export class PaginatedListDataSample {
constructor(json: IPaginatedListDataSample) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListDataSample, simpleProperties as IPaginatedListDataSample)

  this.rows = rows ? [...rows]?.map(p => new DataSample(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<DataSample>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListDataSample {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListDataSample {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<DataSample>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
