/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {HealthcareElement} from './HealthcareElement';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListHealthcareElement {
constructor(json: IPaginatedListHealthcareElement) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListHealthcareElement, simpleProperties as IPaginatedListHealthcareElement)

  this.rows = rows ? [...rows]?.map(p => new HealthcareElement(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<HealthcareElement>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListHealthcareElement {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListHealthcareElement {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<HealthcareElement>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
