/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {HealthcareProfessional} from './HealthcareProfessional';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListHealthcareProfessional {
constructor(json: IPaginatedListHealthcareProfessional) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListHealthcareProfessional, simpleProperties as IPaginatedListHealthcareProfessional)

  this.rows = rows ? [...rows]?.map(p => new HealthcareProfessional(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<HealthcareProfessional>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListHealthcareProfessional {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListHealthcareProfessional {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<HealthcareProfessional>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
