/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {MedicalDevice} from './MedicalDevice';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListMedicalDevice {
constructor(json: IPaginatedListMedicalDevice) {
  Object.assign(this as PaginatedListMedicalDevice, json)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<MedicalDevice>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

}

interface IPaginatedListMedicalDevice {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<MedicalDevice>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}

