/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';
import {User} from './User';

export class PaginatedListUser {
constructor(json: IPaginatedListUser) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListUser, simpleProperties as IPaginatedListUser)

  this.rows = rows ? [...rows]?.map(p => new User(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<User>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListUser {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListUser {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<User>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
