/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';
import {User} from './User';

export class PaginatedListUser {
constructor(json: IPaginatedListUser) {
  Object.assign(this as PaginatedListUser, json)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<User>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

}

interface IPaginatedListUser {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<User>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}

