/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {Coding} from './Coding';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListCoding {
constructor(json: IPaginatedListCoding) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListCoding, simpleProperties as IPaginatedListCoding)

  this.rows = rows ? [...rows]?.map(p => new Coding(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<Coding>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListCoding {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListCoding {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<Coding>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
