/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {MedicalDevice} from './MedicalDevice';
import {PaginatedDocumentKeyAndIdPairObject} from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListMedicalDevice {
constructor(json: IPaginatedListMedicalDevice) {
  const { rows, nextKeyPair, ...simpleProperties } = json

  Object.assign(this as PaginatedListMedicalDevice, json)

  this.rows = rows ? [...rows]?.map(p => new MedicalDevice(p)) : []
  this.nextKeyPair = nextKeyPair && new PaginatedDocumentKeyAndIdPairObject(nextKeyPair)
}

    'pageSize': number;
    'totalSize': number;
    'rows': Array<MedicalDevice>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

    marshal(): IPaginatedListMedicalDevice {
      return {
        ...this,
        rows: this.rows?.map(p => p.marshal()),
        nextKeyPair: this.nextKeyPair?.marshal(),
      }
    }
}

interface IPaginatedListMedicalDevice {
  'pageSize'?: number;
  'totalSize'?: number;
  'rows'?: Array<MedicalDevice>;
  'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;
}
