/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Links (usually for therapeutic reasons) between this patient and healthcare parties (of class PatientHealthcareParty).
*/
export class PatientHealthCareParty {
constructor(json: IPatientHealthCareParty) {
  const { type, ...simpleProperties } = json
  Object.assign(this as PatientHealthCareParty, simpleProperties as IPatientHealthCareParty)
  this.type = type as PatientHealthCarePartyTypeEnum
}

    'type': PatientHealthCarePartyTypeEnum;
    'healthcarePartyId'?: string;

    marshal(): IPatientHealthCareParty {
      return {
        ...this,
      }
    }
}

interface IPatientHealthCareParty {
  'type'?: PatientHealthCarePartyTypeEnum;
  'healthcarePartyId'?: string;
}


export type PatientHealthCarePartyTypeEnum = "doctor" | "referral" | "medicalhouse" | "retirementhome" | "hospital" | "other" | "referringphysician" | "managingorganization" ;
