/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Links (usually for therapeutic reasons) between this patient and healthcare parties (of class PatientHealthcareParty).
*/
export class PatientHealthCareParty {
constructor(json: IPatientHealthCareParty) {
  Object.assign(this as PatientHealthCareParty, json)
}

    'type': PatientHealthCarePartyTypeEnum;
    'healthcarePartyId'?: string;

}

interface IPatientHealthCareParty {
  'type'?: PatientHealthCarePartyTypeEnum;
  'healthcarePartyId'?: string;
}


export type PatientHealthCarePartyTypeEnum = "doctor" | "referral" | "medicalhouse" | "retirementhome" | "hospital" | "other" | "referringphysician" | "managingorganization" ;

