/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PropertyType {
constructor(json: IPropertyType) {
  const { type, ...simpleProperties } = json
  Object.assign(this as PropertyType, simpleProperties as IPropertyType)
  this.type = type as PropertyTypeTypeEnum
}

    'identifier'?: string;
    'type'?: PropertyTypeTypeEnum;

    marshal(): IPropertyType {
      return {
        ...this,
      }
    }
}

interface IPropertyType {
  'identifier'?: string;
  'type'?: PropertyTypeTypeEnum;
}


export type PropertyTypeTypeEnum = "BOOLEAN" | "INTEGER" | "DOUBLE" | "STRING" | "DATE" | "CLOB" | "JSON" ;
