/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SystemMetaDataOwner {
  constructor(json: ISystemMetaDataOwner) {
    const { publicKeysForOaepWithSha256, ...simpleProperties } = json

    Object.assign(this as SystemMetaDataOwner, simpleProperties)

    this.publicKeysForOaepWithSha256 = new Set(json.publicKeysForOaepWithSha256 ?? [])
  }

  'publicKey': string
  'hcPartyKeys': { [key: string]: Array<string> }
  'privateKeyShamirPartitions': { [key: string]: string }
  'aesExchangeKeys': { [key: string]: { [key: string]: { [key: string]: string } } }
  'transferKeys': { [key: string]: { [key: string]: string } }
  'publicKeysForOaepWithSha256': Set<string>

  marshal(): ISystemMetaDataOwner {
    return {
      ...this,
      publicKeysForOaepWithSha256: [...this.publicKeysForOaepWithSha256],
    }
  }
}

interface ISystemMetaDataOwner {
  publicKey?: string
  hcPartyKeys?: { [key: string]: Array<string> }
  privateKeyShamirPartitions?: { [key: string]: string }
  aesExchangeKeys?: { [key: string]: { [key: string]: { [key: string]: string } } }
  transferKeys?: { [key: string]: { [key: string]: string } }
  publicKeysForOaepWithSha256?: Set<string>
}
