/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Telecom {
constructor(json: ITelecom) {
  const { telecomType, ...simpleProperties } = json
  Object.assign(this as Telecom, simpleProperties as ITelecom)
  this.telecomType = telecomType as TelecomTelecomTypeEnum
}

    'telecomType'?: TelecomTelecomTypeEnum;
    'telecomNumber'?: string;
    'telecomDescription'?: string;

    marshal(): ITelecom {
      return {
        ...this,
      }
    }
}

interface ITelecom {
  'telecomType'?: TelecomTelecomTypeEnum;
  'telecomNumber'?: string;
  'telecomDescription'?: string;
}


export type TelecomTelecomTypeEnum = "mobile" | "phone" | "email" | "fax" | "skype" | "im" | "medibridge" | "ehealthbox" | "apicrypt" | "web" | "print" | "disk" | "other" | "pager" ;
