/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A high frequency time-series containing the ts in ms from the start (double) and the values
*/
export class TimeSeries {
constructor(json: ITimeSeries) {
  Object.assign(this as TimeSeries, json)
}

    'fields': Array<string>;
    'samples': Array<Array<number>>;
    'min': Array<number>;
    'max': Array<number>;
    'mean': Array<number>;
    'median': Array<number>;
    'variance': Array<number>;

}

interface ITimeSeries {
  'fields'?: Array<string>;
  'samples'?: Array<Array<number>>;
  'min'?: Array<number>;
  'max'?: Array<number>;
  'mean'?: Array<number>;
  'median'?: Array<number>;
  'variance'?: Array<number>;
}

