/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { DataBuffer } from '../model/DataBuffer';
import { DataSample } from '../model/DataSample';
import { Document } from '../model/Document';
import { Filter } from '../model/Filter';
import { PaginatedListDataSample } from '../model/PaginatedListDataSample';


export class MdDataSampleApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(host: string, headers: any, fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }


     /**
      * 
      * @summary Create a DataSample
      * @param body 
      */
 createOrModifyDataSample(body?: DataSample): Promise<DataSample> {
    let _body = null
    _body = body

    const _url = this.host + `/data/sample` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new DataSample(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Create a batch of Data samples
      * @param body 
      */
 createOrModifyDataSamples(body?: Array<DataSample>): Promise<Array<DataSample>> {
    let _body = null
    _body = body

    const _url = this.host + `/data/sample/batch` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => new DataSample(it))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete a Data sample attachment
      * @param id 
      * @param documentId 
      */
 deleteAttachment(id: string, documentId: string): Promise<string> {
    let _body = null
    
    const _url = this.host + `/data/sample/${encodeURIComponent(String(id))}/attachment/${encodeURIComponent(String(documentId))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete a DataSample
      * @param id 
      */
 deleteDataSample(id: string): Promise<string> {
    let _body = null
    
    const _url = this.host + `/data/sample/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete a batch of Data samples
      * @param ids 
      */
 deleteDataSamples(ids: Array<string>): Promise<Array<string>> {
    let _body = null
    
    const _url = this.host + `/data/sample/batch/${encodeURIComponent(String(ids))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => JSON.parse(JSON.stringify(it)))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Data samples using a filter
      * @param body 
      */
 filterDataSample(body?: Filter): Promise<PaginatedListDataSample> {
    let _body = null
    _body = body

    const _url = this.host + `/data/sample/filter` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new PaginatedListDataSample(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get a DataSample
      * @param id 
      */
 getDataSample(id: string): Promise<DataSample> {
    let _body = null
    
    const _url = this.host + `/data/sample/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new DataSample(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get a DataSample attachment metadata
      * @param id 
      * @param documentId 
      */
 getDataSampleAttachment(id: string, documentId: string): Promise<Document> {
    let _body = null
    
    const _url = this.host + `/data/sample/${encodeURIComponent(String(id))}/attachment/${encodeURIComponent(String(documentId))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new Document(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get a Data sample attachment metadata
      * @param id 
      * @param documentId 
      * @param attachmentId 
      */
 getDataSampleAttachmentContent(id: string, documentId: string, attachmentId: string): Promise<Array<DataBuffer>> {
    let _body = null
    
    const _url = this.host + `/data/sample/${encodeURIComponent(String(id))}/attachment/${encodeURIComponent(String(documentId))}/${encodeURIComponent(String(attachmentId))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => new DataBuffer(it))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Data samples using a filter
      * @param body 
      */
 matchDataSample(body?: Filter): Promise<Array<string>> {
    let _body = null
    _body = body

    const _url = this.host + `/data/sample/match` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => JSON.parse(JSON.stringify(it)))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Create a DataSample
      * @param body 
      * @param id 
      * @param documentId 
      */
 setDataSampleAttachment(id: string, documentId: string, body?: Object): Promise<Document> {
    let _body = null
    _body = body

    const _url = this.host + `/data/sample/${encodeURIComponent(String(id))}/attachment/${encodeURIComponent(String(documentId))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new Document(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}
}

