/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { Filter } from '../model/Filter';
import { MedicalDevice } from '../model/MedicalDevice';
import { PaginatedListMedicalDevice } from '../model/PaginatedListMedicalDevice';


export class MdDeviceApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(host: string, headers: any, fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }


     /**
      * 
      * @summary Create or update a Device
      * @param body 
      */
 createOrModifyMedicalDevice(body?: MedicalDevice): Promise<MedicalDevice> {
    let _body = null
    _body = body

    const _url = this.host + `/medical/device` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new MedicalDevice(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Create or update a batch of Devices
      * @param body 
      */
 createOrModifyMedicalDevices(body?: Array<MedicalDevice>): Promise<Array<MedicalDevice>> {
    let _body = null
    _body = body

    const _url = this.host + `/medical/device/batch` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => new MedicalDevice(it))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete a Device
      * @param id 
      */
 deleteMedicalDevice(id: string): Promise<string> {
    let _body = null
    
    const _url = this.host + `/medical/device/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete Devices
      * @param body 
      */
 deleteMedicalDevices(body?: Array<string>): Promise<Array<string>> {
    let _body = null
    _body = body

    const _url = this.host + `/medical/device/batch` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => JSON.parse(JSON.stringify(it)))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Devices using a filter
      * @param body 
      */
 filterMedicalDevices(body?: Filter): Promise<PaginatedListMedicalDevice> {
    let _body = null
    _body = body

    const _url = this.host + `/medical/device/filter` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new PaginatedListMedicalDevice(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get a Medical Device
      * @param id 
      */
 getMedicalDevice(id: string): Promise<MedicalDevice> {
    let _body = null
    
    const _url = this.host + `/medical/device/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new MedicalDevice(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Devices using a filter
      * @param body 
      */
 matchMedicalDevices(body?: Filter): Promise<Array<string>> {
    let _body = null
    _body = body

    const _url = this.host + `/medical/device/match` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => JSON.parse(JSON.stringify(it)))
      )
      .catch(err => this.handleError(err))
}
}

