/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { Filter } from '../model/Filter';
import { HealthcareElement } from '../model/HealthcareElement';
import { PaginatedListHealthcareElement } from '../model/PaginatedListHealthcareElement';


export class MdHealthcareElementApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(host: string, headers: any, fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }


     /**
      * 
      * @summary Create a Healthcare Element
      * @param body 
      */
 createOrModifyHealthcareElement(body?: HealthcareElement): Promise<HealthcareElement> {
    let _body = null
    _body = body

    const _url = this.host + `/hce` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new HealthcareElement(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Create a Healthcare Element
      * @param body 
      */
 createOrModifyHealthcareElements(body?: Array<HealthcareElement>): Promise<Array<HealthcareElement>> {
    let _body = null
    _body = body

    const _url = this.host + `/hce/batch` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => new HealthcareElement(it))
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete a Healthcare Element
      * @param id 
      */
 deleteHealthcareElement(id: string): Promise<string> {
    let _body = null
    
    const _url = this.host + `/hce/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Healthcare Elements using a filter
      * @param body 
      */
 filterHealthcareElement(body?: Filter): Promise<PaginatedListHealthcareElement> {
    let _body = null
    _body = body

    const _url = this.host + `/hce/filter` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new PaginatedListHealthcareElement(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get a Healthcare Element
      * @param id 
      */
 getHealthcareElement(id: string): Promise<HealthcareElement> {
    let _body = null
    
    const _url = this.host + `/hce/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new HealthcareElement(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Healthcare Elements using a filter
      * @param body 
      */
 matchHealthcareElement(body?: Filter): Promise<Array<string>> {
    let _body = null
    _body = body

    const _url = this.host + `/hce/match` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => JSON.parse(JSON.stringify(it)))
      )
      .catch(err => this.handleError(err))
}
}

