/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { Filter } from '../model/Filter';
import { PaginatedListUser } from '../model/PaginatedListUser';
import { User } from '../model/User';


export class MdUserApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(host: string, headers: any, fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }


     /**
      * 
      * @summary Find Users using a filter
      * @param xIcureToken 
      * @param id 
      */
 checkTokenValidity(xIcureToken: string, id: string): Promise<boolean> {
    let _body = null
    
    const _url = this.host + `/user/token/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
        xIcureToken && (headers = headers.concat(new XHR.Header("x-icure-token", xIcureToken)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Create a User
      * @param body 
      */
 createOrModifyUser(body?: User): Promise<User> {
    let _body = null
    _body = body

    const _url = this.host + `/user` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new User(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Users using a filter
      * @param id 
      */
 createToken(id: string): Promise<string> {
    let _body = null
    
    const _url = this.host + `/user/token/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Delete a User
      * @param id 
      */
 deleteUser(id: string): Promise<string> {
    let _body = null
    
    const _url = this.host + `/user/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              JSON.parse(JSON.stringify(doc.body))
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Users using a filter
      * @param body 
      */
 filterUser(body?: Filter): Promise<PaginatedListUser> {
    let _body = null
    _body = body

    const _url = this.host + `/user/filter` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new PaginatedListUser(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get the logged User
      */
 getLoggedUser(): Promise<User> {
    let _body = null
    
    const _url = this.host + `/user` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new User(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Get a User
      * @param id 
      */
 getUser(id: string): Promise<User> {
    let _body = null
    
    const _url = this.host + `/user/${encodeURIComponent(String(id))}` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              new User(doc.body as JSON)
              
      )
      .catch(err => this.handleError(err))
}

     /**
      * 
      * @summary Find Users using a filter
      * @param body 
      */
 matchUser(body?: Filter): Promise<Array<string>> {
    let _body = null
    _body = body

    const _url = this.host + `/user/match` + "?ts=" + new Date().getTime() 
    let headers = this.headers
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/json"))
    headers = headers.filter(h => h.header !== "Content-Type").concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => 
          
              (doc.body as Array<JSON>).map(it => JSON.parse(JSON.stringify(it)))
      )
      .catch(err => this.handleError(err))
}
}

