/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Encrypted and time-limited Authentication tokens used for inter-applications authentication
*/
export class AuthenticationToken {
constructor(json: IAuthenticationToken) {
  Object.assign(this as AuthenticationToken, json)
}

    /**
    * Encrypted token
    */
    'token': string;
    /**
    * Validity starting time of the token
    */
    'creationTime': number;
    /**
    * Token validity in seconds
    */
    'validity': number;

}

interface IAuthenticationToken {
  'token'?: string;
  'creationTime'?: number;
  'validity'?: number;
}

