/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Codified list of professions exercised by this patient.
*/
export class CodingReference {
constructor(json: ICodingReference) {
  Object.assign(this as CodingReference, json)
}

    'id'?: string;
    'type'?: string;
    'code'?: string;
    'version'?: string;

}

interface ICodingReference {
  'id'?: string;
  'type'?: string;
  'code'?: string;
  'version'?: string;
}

