/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { CodingReference } from './CodingReference';
import { PersonName } from './PersonName';
import { Property } from './Property';
import { SystemMetaDataOwner } from './SystemMetaDataOwner';

export class HealthcareProfessional {
    /**
    * the Id of the healthcare party. We encourage using either a v4 UUID or a HL7 Id.
    */
    'id'?: string;
    /**
    * the revision of the healthcare party in the database, used for conflict management / optimistic locking.
    */
    'rev'?: string;
    /**
    * creation timestamp of the object.
    */
    'created'?: number;
    /**
    * last modification timestamp of the object.
    */
    'modified'?: number;
    /**
    * the soft delete timestamp. When a user is ”deleted“, this is set to a non null value: the moment of the deletion
    */
    'deletionDate'?: number;
    /**
    * The full name of the healthcare party, used mainly when the healthcare party is an organization
    */
    'name'?: string;
    /**
    * the lastname (surname) of the healthcare party. This is the official lastname that should be used for official administrative purposes.
    */
    'lastName'?: string;
    /**
    * the firstname (name) of the healthcare party.
    */
    'firstName'?: string;
    /**
    * the list of all names of the healthcare party, also containing the official full name information. Ordered by preference of use. First element is therefore the official name used for the healthcare party in the application
    */
    'names': Array<PersonName>;
    /**
    * the gender of the healthcare party: male, female, indeterminate, changed, changedToMale, changedToFemale, unknown
    */
    'gender'?: HealthcareProfessionalGenderEnum;
    /**
    * Mr., Ms., Pr., Dr. ...
    */
    'civility'?: string;
    /**
    * Medical specialty of the healthcare party
    */
    'speciality'?: string;
    /**
    * Id of parent of the user representing the healthcare party.
    */
    'parentId'?: string;
    /**
    * The list of addresses (with address type).
    */
    'addresses': Array<Address>;
    /**
    * The list of languages spoken by the patient ordered by fluency (alpha-2 code http://www.loc.gov/standards/iso639-2/ascii_8bits.html).
    */
    'languages': Array<string>;
    /**
    * A picture usually saved in JPEG format.
    */
    'picture'?: string;
    /**
    * Medical specialty of the healthcare party codified using FHIR or Kmehr codificaiton scheme
    */
    'specialityCodes': Set<CodingReference>;
    /**
    * Text notes.
    */
    'notes'?: string;
    'properties': Set<Property>;
    'systemMetaData'?: SystemMetaDataOwner;

}


export type HealthcareProfessionalGenderEnum = "male" | "female" | "indeterminate" | "changed" | "changedToMale" | "changedToFemale" | "unknown" ;

