/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataSample } from './DataSample';
import { PaginatedDocumentKeyAndIdPairObject } from './PaginatedDocumentKeyAndIdPairObject';

export class PaginatedListDataSample {
    'pageSize': number;
    'totalSize': number;
    'rows': Array<DataSample>;
    'nextKeyPair'?: PaginatedDocumentKeyAndIdPairObject;

}

