/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TypedValueObject {
    'type'?: TypedValueObjectTypeEnum;
    'booleanValue'?: boolean;
    'integerValue'?: number;
    'doubleValue'?: number;
    'stringValue'?: string;
    'dateValue'?: Date;

}


export type TypedValueObjectTypeEnum = "BOOLEAN" | "INTEGER" | "DOUBLE" | "STRING" | "DATE" | "CLOB" | "JSON" ;

